#!/bin/bash
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DESINSTALAR SCRIPT • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e
echo -e "\033[0;33mLIMPANDO ARQUÍVOS...\033[0m"
sleep 1s
rm -rf connect_ssh
echo -e
echo -e "\033[0;33mLIMPANDO CACHÊ...\033[0m"
sleep 2s
rm -rf run && rm -rf menu && rm -rf uninstall_script
clear
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\E[41;1;37m     • DESINSTALADO COM SUCESSO! • \E[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
sleep 4s
clear
exit
